version: "3.7"
services:
  geyser:
    # Bedrock server
    # https://hub.docker.com/r/itzg/minecraft-bedrock-server
    image: itzg/minecraft-bedrock-server:latest
    container_name: bedrock
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    volumes:
      - bedrock-data:/data
    environment:
      - SERVER_NAME=SoyukkeDev
      - SERVER_PORT=19132
      - EULA=TRUE
      - GAMEMODE=survival
      - DIFFICULTY=normal
      - MAX_THREADS=0

volumes:
  bedrock-data:
